include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - test

code_quality:
  artifacts:
    paths: [gl-code-quality-report.json]
    expire_in: 1 day

code_quality_html:
  extends: code_quality
  variables:
    REPORT_FORMAT: html
  artifacts:
    paths: [gl-code-quality-report.html]
    expire_in: 1 day

